apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-load-balancer-conf
  namespace: kube-system
data:
    use-forwarded-headers: "true"
    log-format-escape-json: "true"
    log-format-upstream: '
    {
      "app": "nginx-k8s",
      "timestamp": "$time_iso8601", 
      "remote_addr": "$remote_addr",
      "remote_user": "$remote_user",
      "request": "$request",
      "request_method": "$request_method",
      "status": "$status",
      "body_bytes_sent": "$body_bytes_sent",
      "http_referer": "$http_referer",
      "http_user_agent": "$http_user_agent",
      "request_length": "$request_length",
      "request_time": "$request_time",
      "proxy_upstream_name": "$proxy_upstream_name",
      "upstream_connect_time": "$upstream_connect_time",
      "upstream_response_length": "$upstream_response_length",
      "upstream_response_time": "$upstream_response_time",
      "upstream_status": "$upstream_status",
      "req_id": "$req_id",
      "namespace": "$namespace",
      "ingress_name": "$ingress_name",
      "service_name": "$service_name",
      "service_port": "$service_port"
    }
    '