version: 1
formatters:
  json:
    (): 'custom_formatter.CustomJSONFormatter'
    app: 'myExampleApp'
    format: '%(process)d %(asctime)s %(name)s %(levelname)s %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: json
    stream: ext://sys.stdout
loggers:
  basic:
    level: DEBUG
    handlers: [console]
    propagate: no
root:
  level: DEBUG
  handlers: [console]