version: 1
formatters:
  basic:
    (): 'custom_formatter.CustomJSONFormatter'
    app: 'myExampleApp'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: basic
    stream: ext://sys.stdout
loggers:
  basic:
    level: DEBUG
    handlers: [console]
    propagate: no
root:
  level: DEBUG
  handlers: [console]