version: '3.8'

x-logging: &loki-logging
    driver: loki
    options:
        loki-url: "http://localhost:3100/loki/api/v1/push"

services:
    web:
        image: chealexey/public_repo:django_log
        logging: *loki-logging

    nginx:
        image: nginx:latest
        depends_on:
            - web
        ports:
            - "8000:8000"
        volumes:
            - ./conf/nginx.conf:/etc/nginx/nginx.conf
        logging: *loki-logging